/**
 * DocuMind AI - Export Utility
 * Reliably exports AI answers, summaries, study notes, MCQs, flashcards, and comparison reports
 * to Markdown (.md), Plain Text (.txt), Word/HTML (.doc), and Printable PDF format.
 */

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportToMarkdown(title: string, markdownContent: string, filename = 'documind-export.md') {
  const header = `# ${title}\n*Generated by DocuMind AI – Turn Your Documents Into Intelligence*\n*Date: ${new Date().toLocaleDateString()}*\n\n---\n\n`;
  downloadFile(header + markdownContent, filename, 'text/markdown;charset=utf-8');
}

export function exportToTxt(title: string, content: string, filename = 'documind-export.txt') {
  const header = `${title.toUpperCase()}\nGenerated by DocuMind AI\nDate: ${new Date().toLocaleDateString()}\n----------------------------------------\n\n`;
  downloadFile(header + content, filename, 'text/plain;charset=utf-8');
}

export function exportToPrint(title: string, htmlOrMarkdownContent: string) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to print or save as PDF.');
    return;
  }

  // Basic markdown to clean HTML conversion
  const formattedHtml = htmlOrMarkdownContent
    .replace(/^### (.*$)/gim, '<h3 style="color:#1c4e48;margin-top:16px;margin-bottom:8px;">$1</h3>')
    .replace(/^## (.*$)/gim, '<h2 style="color:#1c4e48;margin-top:20px;margin-bottom:8px;border-bottom:1px solid #d4e0dd;padding-bottom:4px;">$1</h2>')
    .replace(/^# (.*$)/gim, '<h1 style="color:#1c4e48;margin-top:24px;margin-bottom:12px;">$1</h1>')
    .replace(/\*\*(.*?)\*\*/gim, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/gim, '<em>$1</em>')
    .replace(/^\s*-\s+(.*$)/gim, '<li style="margin-bottom:4px;">$1</li>')
    .replace(/\n\n/gim, '</p><p style="margin-bottom:12px;line-height:1.6;">')
    .replace(/\[Source: (.*?)\]/gim, '<span style="background:#e8f4f1;color:#1c4e48;padding:2px 6px;border-radius:4px;font-size:12px;">Source: $1</span>');

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title} - DocuMind AI</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            color: #183237;
            padding: 32px;
            max-width: 800px;
            margin: 0 auto;
            line-height: 1.6;
          }
          .header {
            border-bottom: 2px solid #1c4e48;
            padding-bottom: 16px;
            margin-bottom: 24px;
          }
          .logo {
            font-size: 20px;
            font-weight: bold;
            color: #1c4e48;
          }
          .subtitle {
            font-size: 12px;
            color: #5e7a76;
          }
          .footer {
            margin-top: 40px;
            border-top: 1px solid #e8efed;
            padding-top: 12px;
            font-size: 11px;
            color: #5e7a76;
            display: flex;
            justify-content: space-between;
          }
          ul { padding-left: 20px; }
          table { width: 100%; border-collapse: collapse; margin: 16px 0; }
          th, td { border: 1px solid #d4e0dd; padding: 8px 12px; text-align: left; font-size: 13px; }
          th { background: #f0f7f5; color: #1c4e48; }
          @media print {
            body { padding: 0; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">DocuMind AI</div>
          <div class="subtitle">Intelligent Document & Personalized Learning Assistant • Grounded Factual RAG</div>
        </div>
        <h1 style="color:#1c4e48;font-size:24px;">${title}</h1>
        <p style="font-size:12px;color:#5e7a76;">Generated on ${new Date().toLocaleDateString('en-US', { dateStyle: 'full' })}</p>
        <div class="content">
          <p>${formattedHtml}</p>
        </div>
        <div class="footer">
          <span>Verified Grounded Document Intelligence</span>
          <span>DocuMind AI</span>
        </div>
        <script>
          window.onload = function() {
            setTimeout(function() { window.print(); }, 250);
          }
        </script>
      </body>
    </html>
  `);
  printWindow.document.close();
}

export const exportAsMarkdown = exportToMarkdown;
export const exportAsPlainText = exportToTxt;
export const exportAsPrintableReport = exportToPrint;
